LOCAL_PATH := device/lge/ms330

## Platform
TARGET_BOARD_PLATFORM := msm8909
TARGET_BOARD_PLATFORM_GPU := qcom-adreno304

### Bootloader
BOOTLOADER_PLATFORM := msm8909 #use msm8952 LK configuration
TARGET_BOOTLOADER_BOARD_NAME := m1
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true

## CPU
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_ARCH_VARIANT_CPU := cortex-a9
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_SMP := true
 
BOARD_CANT_BUILD_RECOVERY_FROM_BOOT_PATCH := true

## Init
TARGET_INIT_VENDOR_LIB := libinit_m1
# TARGET_RECOVERY_UPDATER_LIBS :=
BOARD_HAL_STATIC_LIBRARIES := libhealthd.m1
TARGET_PLATFORM_DEVICE_BASE := /devices/soc.0/
TARGET_USES_OVERLAY := true

# Kernel
TARGET_KERNEL_SOURCE := kernel/lge/m1
TARGET_KERNEL_CONFIG := m1_defconfig
BOARD_KERNEL_SEPARATED_DT := true
ENABLE_CPUSETS := true

BOARD_KERNEL_CMDLINE := console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0
BOARD_KERNEL_CMDLINE += msm_rtb.filter=0x3F lpm_levels.sleep_disabled=1
BOARD_KERNEL_CMDLINE += user_debug=31 ehci-hcd.park=3 earlyprintk
BOARD_KERNEL_CMDLINE += androidboot.bootdevice=7824900.sdhci
BOARD_KERNEL_CMDLINE += androidboot.selinux=permissive
BOARD_KERNEL_CMDLINE += androidboot.hardware=m1

BOARD_KERNEL_PAGESIZE	:= 2048
BOARD_KERNEL_BASE 		 := 0x00000000
BOARD_KERNEL_OFFSET		 := 0x00008000
BOARD_KERNEL_TAGS_OFFSET := 0x00000100
BOARD_RAMDISK_OFFSET	 := 0x02000000
BOARD_KERNEL_SECOND_OFFSET := 0x00f00000

BOARD_MKBOOTIMG_ARGS	:= --base $(BOARD_KERNEL_BASE)
BOARD_MKBOOTIMG_ARGS	+= --kernel_offset $(BOARD_KERNEL_OFFSET)
BOARD_MKBOOTIMG_ARGS	+= --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS	+= --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS	+= --second_offset $(BOARD_KERNEL_SECOND_OFFSET)

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE 		:= 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE 	:= 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE 	:= 2524971008
BOARD_USERDATAIMAGE_PARTITION_SIZE 	:= 4848615424
BOARD_CACHEIMAGE_PARTITION_SIZE		:= 209715200

BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PERSISTIMAGE_FILE_SYSTEM_TYPE := ext4

BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_VOLD_EMMC_SHARES_DEV_MAJOR := true

TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TARGET_KERNEL_HAVE_EXFAT := true
# TARGET_KERNEL_HAVE_NTFS := true

# Use HW crypto for ODE
TARGET_HW_DISK_ENCRYPTION := true

BOARD_CANT_BUILD_RECOVERY_FROM_BOOT_PATCH := true 
# TARGET_NOT_USE_GZIP_RECOVERY_RAMDISK := true



# QCOM hardware
BOARD_USES_QCOM_HARDWARE := true
TARGET_USES_ION := true
TARGET_USES_NEW_ION_API :=true
TARGET_USES_QCOM_BSP := true
TARGET_ENABLE_QC_AV_ENHANCEMENTS := true

# GPS
BOARD_VENDOR_QCOM_GPS_LOC_API_HARDWARE := default
BOARD_VENDOR_QCOM_LOC_PDK_FEATURE_SET := true
TARGET_NO_RPC := true

# Camera
# USE_CAMERA_STUB := true
USE_DEVICE_SPECIFIC_CAMERA := true

# Wifi
WLAN_PATH = wlan-caf
BOARD_HAS_QCOM_WLAN              := true
BOARD_WLAN_DEVICE                := qcwcn
BOARD_HOSTAPD_DRIVER             := NL80211
BOARD_HOSTAPD_PRIVATE_LIB        := lib_driver_cmd_$(BOARD_WLAN_DEVICE)
BOARD_WPA_SUPPLICANT_DRIVER      := NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_$(BOARD_WLAN_DEVICE)
WIFI_DRIVER_FW_PATH_AP           := "ap"
WIFI_DRIVER_FW_PATH_STA          := "sta"
WIFI_DRIVER_FW_PATH_P2P          := "p2p"
WPA_SUPPLICANT_VERSION           := VER_0_8_X
TARGET_USES_WCNSS_CTRL           := true
TARGET_USES_QCOM_WCNSS_QMI       := true

# Display
TARGET_CONTINUOUS_SPLASH_ENABLED := true
TARGET_USES_C2D_COMPOSITION := true
TARGET_USES_OVERLAY := true
BOARD_EGL_CFG := $(LOCAL_PATH)/egl.cfg
MAX_EGL_CACHE_KEY_SIZE := 12*1024
MAX_EGL_CACHE_SIZE := 2048*1024
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3
HAVE_ADRENO_SOURCE:= false
OVERRIDE_RS_DRIVER:= libRSDriver_adreno.so
USE_OPENGL_RENDERER := true
TARGET_FORCE_HWC_FOR_VIRTUAL_DISPLAYS := true

# Lights
TARGET_PROVIDES_LIBLIGHT := true

# QCRIL
TARGET_RIL_VARIANT := caf
FEATURE_QCRIL_UIM_SAP_SERVER_MODE := true

# Power
TARGET_POWERHAL_VARIANT := qcom

# Enable sensor multi HAL
# USE_SENSOR_MULTI_HAL := true

# Qualcomm support
BOARD_USES_QCOM_HARDWARE := true
BOARD_USES_QC_TIME_SERVICES := true
# PRODUCT_BOOT_JARS += tcmiface tcmclient com.qti.dpmframework dpmapi com.qti.location.sdk

# ANT+
BOARD_ANT_WIRELESS_DEVICE := "qualcomm-smd"

# QCNE (Qualcomm ConNectivity Engine)
BOARD_USES_QCNE := true
BOARD_USES_DPM := true
TARGET_LDPRELOAD := libNimsWrap.so

# Audio
BOARD_USES_ALSA_AUDIO := true
USE_CUSTOM_AUDIO_POLICY := 1
TARGET_USES_QCOM_MM_AUDIO := true

AUDIO_FEATURE_ENABLED_KPI_OPTIMIZE := true
AUDIO_FEATURE_ENABLED_NEW_SAMPLE_RATE := true

AUDIO_FEATURE_ENABLED_ANC_HEADSET := true
AUDIO_FEATURE_ENABLED_COMPRESS_CAPTURE := true
AUDIO_FEATURE_ENABLED_COMPRESS_VOIP := true
AUDIO_FEATURE_ENABLED_EXTN_FORMATS := true
AUDIO_FEATURE_ENABLED_EXTN_FLAC_DECODER := true
AUDIO_FEATURE_ENABLED_EXTN_RESAMPLER := true
AUDIO_FEATURE_ENABLED_FM := true
AUDIO_FEATURE_ENABLED_FLUENCE := true
AUDIO_FEATURE_ENABLED_HFP := true
AUDIO_FEATURE_ENABLED_INCALL_MUSIC := true
AUDIO_FEATURE_ENABLED_MULTI_VOICE_SESSIONS := true
AUDIO_FEATURE_ENABLED_PCM_OFFLOAD := true
AUDIO_FEATURE_ENABLED_PROXY_DEVICE := true
AUDIO_FEATURE_ENABLED_SSR := true
AUDIO_FEATURE_ENABLED_USBAUDIO := true
AUDIO_FEATURE_ENABLED_VOICE_CONCURRENCY := true
AUDIO_FEATURE_ENABLED_WFD_CONCURRENCY := true
AUDIO_FEATURE_ENABLED_RECORD_PLAY_CONCURRENCY := true
BOARD_USES_SRS_TRUEMEDIA := true
DOLBY_DAP := true
DOLBY_DDP := true
DOLBY_UDC := true
DOLBY_UDC_MULTICHANNEL := true
DOLBY_UDC_STREAMING_HLS := true
MM_AUDIO_ENABLED_FTM := true
MM_AUDIO_ENABLED_SAFX := true

# Bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_QCOM := true
BLUETOOTH_HCI_USE_MCT := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := $(LOCAL_PATH)/bluetooth
QCOM_BT_USE_BTNV := true

# Crypto
TARGET_HW_DISK_ENCRYPTION := true
TARGET_KEYMASTER_WAIT_FOR_QSEE := true

# FM
AUDIO_FEATURE_ENABLED_FM_POWER_OPT := true
TARGET_QCOM_NO_FM_FIRMWARE := true

# Bootanimation
TARGET_BOOTANIMATION_PRELOAD := true
TARGET_BOOTANIMATION_TEXTURE_CACHE := true

# Media
TARGET_HAVE_SIGNED_VENUS_FW := true

# Hardware
BOARD_USES_CYANOGEN_HARDWARE := true
BOARD_HARDWARE_CLASS += hardware/cyanogen/cmhw
TARGET_TAP_TO_WAKE_NODE := /sys/devices/virtual/input/lge_touch/lpwg_data

# SEPolicy
include device/qcom/sepolicy/sepolicy.mk
BOARD_SEPOLICY_DIRS += $(LOCAL_PATH)/sepolicy

# Offmode Charging
BOARD_CHARGER_ENABLE_SUSPEND := true
COMMON_GLOBAL_CFLAGS += \
    -DBOARD_CHARGING_CMDLINE_NAME='"androidboot.mode"' \
    -DBOARD_CHARGING_CMDLINE_VALUE='"chargerlogo"'

# Recovery
BOARD_HAS_DOWNLOAD_MODE := true
BOARD_HAS_NO_MISC_PARTITION := true
BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_RECOVERY_SWIPE := true
BOARD_SUPPRESS_EMMC_WIPE := true
BOARD_SUPPRESS_SECURE_ERASE := true
BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_15x24.h\"
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TARGET_RECOVERY_FSTAB := $(LOCAL_PATH)/rootdir/recovery.fstab
TARGET_RECOVERY_PIXEL_FORMAT := "RGB_565"

### TWRP
# RECOVERY_VARIANT := twrp
# TARGET_RECOVERY_FSTAB := $(LOCAL_PATH)/rootdir/etc/twrp.fstab
TW_THEME := portrait_hdpi
TW_INTERNAL_STORAGE_PATH := "/data/media"
TW_INTERNAL_STORAGE_MOUNT_POINT := "data"
TW_EXTERNAL_STORAGE_PATH := "/external_sd"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "external_sd"
TW_DEFAULT_EXTERNAL_STORAGE := true
TARGET_RECOVERY_QCOM_RTC_FIX := true
# TW_DEFAULT_EXTERNAL_STORAGE := true
TW_INCLUDE_CRYPTO := true
RECOVERY_SDCARD_ON_DATA := true
# BOARD_HAS_NO_REAL_SDCARD := true
TW_EXCLUDE_SUPERSU := true
TW_DEFAULT_BRIGHTNESS := 179
TW_MAX_BRIGHTNESS := 255
TW_NO_SCREEN_TIMEOUT := true
# TW_EXTRA_LANGUAGES := true
TW_TARGET_USES_QCOM_BSP := true
TW_NEW_ION_HEAP := true
# TW_INCLUDE_NTFS_3G := true
TWRP_INCLUDE_LOGCAT := true
TARGET_USES_LOGD := true
# TW_USE_TOOLBOX := true

BOARD_WIDEVINE_OEMCRYPTO_LEVEL := 3

ifneq ($(QCPATH),)
-include $(QCPATH)/common/msm8909/BoardConfigVendor.mk

#USESECIMAGETOOL := true
# Gensecimage generation of signed apps bootloader
#QTI_GENSECIMAGE_MSM_IDS := 8909
# Use signed image as default
#QTI_GENSECIMAGE_SIGNED_DEFAULT := 8909
#SECIMAGE tool feature flags
#export USES_SEC_POLICY_DEFAULT_SUBFOLDER_SIGN=1
#export USES_SEC_POLICY_INTEGRITY_CHECK=1
endif