# /etc/bashrc
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi

use_color=false

# enable colorful terminal
if [[ ${EUID} == 0 ]] ; then
	PS1='\[\033[01;32m\]\[\033[01;34m\] \w \$\[\033[00m\] ' 
else
	PS1='\[\033[01;32m\]\u@\h\[\033[01;34m\] \w \$\[\033[00m\] '
fi

# Set up a ton of aliases to cover toolbox with the nice busybox
# equivalents of its commands
# for i in cat chmod chown df insmod ln lsmod mkdir mount mv rm rmdir rmmod umount; do
# 	eval alias ${i}=\"busybox ${i}\"
# done
# unset i

# Bash won't get SIGWINCH if another process is in the foreground.
# Enable checkwinsize so that bash will check the terminal size when
# it regains control.  #65623
# http://cnswww.cns.cwru.edu/~chet/bash/FAQ (E11)
shopt -s checkwinsize
shopt -s histappend
shopt -s autocd
shopt -s dotglob
shopt -s dirspell
shopt -s direxpand
shopt -s cdspell


export EDITOR='/sbin/nano'
export HISTFILE='/sdcard/TWRP/.bash_history'
export HISTFILESIZE=
export HISTSIZE=
export HISTTIMEFORMAT="[%F %T] "
export HOME='/'
export INPUTRC='/etc/inputrc'
export TERM=xterm
PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias ls='busybox ls --color=auto'
alias ll='busybox ls -la --color=auto'
alias lsh='busybox ls -lha --color=auto'
alias lsht='busybox ls -lhatr --color=auto'
alias cpr='busybox cp -R'


alias ifind='find -iname'
alias fin='find . -type f | sort | grep -F -H -n -i'
alias finzero='find . -type f -size +1c -exec grep -m 1 -LE "[^\0]" {} \;'

alias lsp='busybox ls -l --color=auto /dev/block/platform/msm_sdcc.1/by-name'

alias env='set | sort'

alias sysro='mount -o remount,ro /system'
alias sysrw='mount -o remount,rw /system'

# Try to keep environment pollution down, CBS cancelled Walker.
unset use_color safe_term match_lhs

resize
